# Generated by Django 5.2 on 2025-06-28 22:18

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Perfil')),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Tasa de interés mensual. Ej: 1.91 para 1.91%', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa de Interés Nominal Mensual (%)')),
                ('guarantee_percentage', models.DecimalField(decimal_places=2, help_text='Porcentaje sobre el monto solicitado para el afianzamiento.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Porcentaje de Afianzamiento (%)')),
                ('guarantee_vat_percentage', models.DecimalField(decimal_places=2, default=19.0, help_text='Porcentaje de IVA que se aplica sobre el valor del afianzamiento. Ej: 19.00', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='IVA del Afianzamiento (%)')),
                ('grace_period_days', models.IntegerField(help_text='Número de días para el cálculo del interés de carencia.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Días de Interés de Carencia')),
                ('insurance_percentage', models.DecimalField(decimal_places=2, help_text='Porcentaje sobre el monto solicitado para el seguro de vida.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Porcentaje de Seguro (%)')),
                ('broker_commission_percentage', models.DecimalField(decimal_places=2, help_text='Porcentaje de comisión para el corredor autorizado.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Comisión del Corredor (%)')),
            ],
            options={
                'verbose_name': 'Perfil de Crédito',
                'verbose_name_plural': 'Perfiles de Crédito',
                'ordering': ['name'],
            },
        ),
    ]
