# Generated by Django 5.2.3 on 2025-06-30 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditprofile',
            name='broker_commission_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de comisión para el corredor autorizado.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Comisión del Corredor (%)'),
        ),
        migrations.AlterField(
            model_name='creditprofile',
            name='grace_period_days',
            field=models.IntegerField(blank=True, help_text='Número de días para el cálculo del interés de carencia.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Días de Interés de Carencia'),
        ),
        migrations.AlterField(
            model_name='creditprofile',
            name='guarantee_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje sobre el monto solicitado para el afianzamiento.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Porcentaje de Afianzamiento (%)'),
        ),
        migrations.AlterField(
            model_name='creditprofile',
            name='guarantee_vat_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=19.0, help_text='Porcentaje de IVA que se aplica sobre el valor del afianzamiento. Ej: 19.00', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='IVA del Afianzamiento (%)'),
        ),
        migrations.AlterField(
            model_name='creditprofile',
            name='insurance_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje sobre el monto solicitado para el seguro de vida.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Porcentaje de Seguro (%)'),
        ),
        migrations.AlterField(
            model_name='creditprofile',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tasa de interés mensual. Ej: 1.91 para 1.91%', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa de Interés Nominal Mensual (%)'),
        ),
    ]
